### ISSUE TITLE
Question about esp8266-mesh

### ISSUE THREAD

**Issue by RudyFiero** [EricMiddleton1/esp8266-mesh#1]
A quick question (hopefully).  It seems to me that you are using UDP rather than TCP for mesh transfers. Do you, or do you have planned, a mechanism to handle undelivered/error packets? Any idea when you might have some documentation about using your project?

I design electronic hardware for work but have been getting into programming as a hobbie. I have tried other mesh projects but had been disappointed with the implementations. I had thought of doing my own but I really don't have the time to learn all that I would need to know. I like the efficiency of UDP but I also want to know if a packet didn't get to where it needed to go. Of course this could be implemented in the application level.

Quite a while ago I tried the ESP8266 Arduino mesh example and it was horrible. I spent a lot of time testing Coopdis/easyMesh. I spent some time trying https://gitlab.com/BlackEdder/painlessMesh that was a derivative of easyMesh.

**Comment by EricMiddleton1** [comment]
> Any idea when you might have some documentation about using your project?

I started this project only a couple of weeks ago and a lot of necessary functionality is not implemented. Additionally, none of the implemented features have been sufficiently tested. More specifically, the following features are implemented:
- Physical mesh construction. The nodes will connect to each other and create a network
- Routing. Each device builds its own graph of the network that it uses for packet routing
- Network testing. A built-in ping/traceroute packet is implemented that allows for the network to be tested

The following (critically important) features are not implemented:
- User message passing. There is currently no way to send an application layer message to another node in the network. This means that the project isn't really useful for anyone yet
- This project currently uses the Arduino networking libraries which are not designed for high performance. I plan to switch all of the networking to directly use the esp8266 SDK instead, which provides the highest performance possible for this chip 
- Testing. There's no formal testing in place to make sure that everything is working properly

Once I complete the minimum required functionality to make this project usable, I'll make some documentation for using it.

> It seems to me that you are using UDP rather than TCP for mesh transfers. Do you, or do you have planned, a mechanism to handle undelivered/error packets?

I have no plans at this time to support anything other than UDP. Because this project (and all other ESP8266 mesh networks I've seen) do not create an IP mesh network, using TCP will require individual point-to-point TCP connections to be established at every hop of the route that a message takes. This overhead is more than I would like to have. My plan at this point is to provide a "best effort" message delivery system, with the expectation that the application will provide any error checking/re-transmitting that is necessary. I may consider adding this to the library if it's a popular request.

> Quite a while ago I tried the ESP8266 Arduino mesh example and it was horrible. I spent a lot of time testing Coopdis/easyMesh. I spent some time trying https://gitlab.com/BlackEdder/painlessMesh that was a derivative of easyMesh.

I just took a look at painlessMesh, and it looks pretty mature. If you need something soon, I would recommend using that one. That being said, there are a few things about the structure of my project that may give it a higher performance over some of the other mesh networks for the ESP:
- My network allows for loops in the network topology. painlessMesh (and others) use star topologies, which means that there's only one path between a pair of nodes. My network can have multiple, redundant paths between nodes, which can improve performance of a highly dynamic network, or a network with heavy traffic
- My network is a [link-state routing protocol](https://en.wikipedia.org/wiki/Link-state_routing_protocol). Periodically (currently every 2.5 seconds), each node constructs a shortest path tree to each other node in the network. This shortest path computation uses information about the health of each link, which means that the network will respond quickly and reliably to changes in link performance (such as interference)
- My network uses binary messages for everything. This will increase performance over JSON (which is used in other implementations), but this difference may not be noticeable

**Comment by RudyFiero** [comment]
Thank you for such a detailed answer.  I like what you have described. I'm looking forward to try it. I am not looking for an immediate solution. I am interested in helping with testing when you have enough functionality implemented.
